model_list = [
    'audi a1',
    'audi a3',
    'audi a4',
    'audi a5',
    'audi a6',
    'audi a7',
    'audi a8',
    'bmw 1 series',
    'bmw 2 series',
    'bmw 3 series',
    'bmw 4 series',
    'bmw 5 series',
    'bmw 6 series',
    'bmw 7 series',
    'bmw i3',
    'bmw i8',
    'cadillac escalade',
    'dacia duster',
    'dacia logan',
    'dacia sandero',
    'dodge challenger srt',
    'dodge charger srt',
    'dodge ram',
    'ferrari california',
    'ferrari enzo',
    'ferrari la ferrari',
    'fiat cinquecento',
    'fiat multipla',
    'fiat panda',
    'fiat spider',
    'goggomobil ts250',
    'honda civic',
    'honda jazz',
    'honda nsx',
    'hyundai tucson',
    'lada niva',
    'mazda 3',
    'mazda cx5',
    'mazda miata',
    'mazda rx8',
    'mazda5',
    'mercedes a-class',
    'mercedes b-class',
    'mercedes c-class',
    'mercedes e-class',
    'mercedes g-class',
    'mercedes m-class',
    'mercedes s-class',
    'mercedes sls amg',
    'opel adam',
    'opel admiral',
    'opel astra',
    'opel corsa',
    'opel grandland x',
    'opel insignia',
    'opel combo',
    'porsche 911 gt3',
    'porsche 944',
    'porsche cayenne',
    'porsche panamera',
    'subaru impreza',
    'tata nano',
    'vw golf 7',
    'vw jetta',
    'vw passat',
    'vw tiguan',
    'vw tuareg']

body = [
    'Cabrio',
    'Coupé',
    'Hatchback',
    'Station Wagon',
    'Limousine',
    'Van',
    'Pickup Truck',
    'SUV',
    'Sports Car'
]
