model_dict = {
    'audi a1': 'skip',
    'audi a3': 'skip',
    'audi a4': 'skip',
    'audi a5': 'skip',
    'audi a6': 'skip',
    'audi a7': 'skip',
    'audi a8': 'skip',
    'bmw 1 series': 'skip',
    'bmw 2 series': 'skip',
    'bmw 3 series': 'skip',
    'bmw 4 series': 'skip',
    'bmw 5 series': 'skip',
    'bmw 6 series': 'skip',
    'bmw 7 series': 'skip',
    'bmw i3': '',
    'bmw i8': '',
    'cadillac escalade': '',
    'dacia duster': '',
    'dacia logan': '',
    'dacia sandero': '',
    'dodge challenger srt': '',
    'dodge charger srt': '',
    'dodge ram': '',
    'ferrari california': '',
    'ferrari enzo': '',
    'ferrari la ferrari': '',
    'fiat cinquecento': '',
    'fiat multipla': '',
    'fiat panda': '',
    'fiat spider': '',
    'goggomobil ts250': '',
    'honda civic': '',
    'honda jazz': '',
    'honda nsx': '',
    'hyundai tucson': '',
    'lada niva': '',
    'mazda 3': '',
    'mazda cx5': '',
    'mazda miata': '',
    'mazda rx8': '',
    'mazda5': '',
    'mercedes a-class': '',
    'mercedes b-class': '',
    'mercedes c-class': '',
    'mercedes e-class': '',
    'mercedes g-class': '',
    'mercedes m-class': '',
    'mercedes s-class': '',
    'mercedes sls amg': '',
    'opel adam': '',
    'opel admiral': '',
    'opel astra': '',
    'opel corsa': '',
    'opel grandland x': '',
    'opel insignia': '',
    'opel combo': '',
    'porsche 911 gt3': '',
    'porsche 944': '',
    'porsche cayenne': '',
    'porsche panamera': '',
    'subaru impreza': '',
    'tata nano': '',
    'vw golf 7': '',
    'vw jetta': '',
    'vw passat': '',
    'vw tiguan': '',
    'vw tuareg': ''
}

